[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    Tag               docker.*
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  2
    Read_from_Head    false

[FILTER]
    Name    grep
    Match   docker.*
    Regex   log .*\"event\":\"sip_(invite|answer|bye)\"

[FILTER]
    Name         parser
    Match        docker.*
    Key_Name     log
    Parser       kamailio_json_line
    Reserve_Data True

[FILTER]
    Name         parser
    Match        docker.*
    Key_Name     sip_json
    Parser       json
    Reserve_Data True

[FILTER]
    Name    modify
    Match   docker.*
    Remove  log
    Remove  sip_json

[OUTPUT]
    Name                opensearch
    Match               docker.*
    Host                opensearch-node1
    Port                9200
    HTTP_User           admin
    HTTP_Passwd         1Qazxsw@3edc
    Index               sip-calls
    Logstash_Format     Off
    Suppress_Type_Name  On
    tls                 On
    tls.verify          Off